import type { Book } from './types';

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    coverImage: 'https://placehold.co/300x450/89b7e5/2a3f5c',
    'data-ai-hint': 'vintage book',
    description: 'A novel about the American dream, set in the Roaring Twenties. It tells the story of the mysterious millionaire Jay Gatsby and his obsession for the beautiful Daisy Buchanan.',
    tags: ['Classic', 'Fiction', 'Tragedy'],
    language: 'English',
    content: 'In my younger and more vulnerable years my father gave me some advice that I’ve been turning over in my mind ever since...',
    readingProgress: 25,
  },
  {
    id: '2',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    coverImage: 'https://placehold.co/300x450/9ca3da/2a2e45',
    'data-ai-hint': 'scholarly book',
    description: 'A novel about the seriousness of the problems of racism, prejudice, and injustice, as seen through the eyes of a young girl named Scout Finch.',
    tags: ['Classic', 'Fiction', 'Legal Drama'],
    language: 'English',
    content: 'When he was nearly thirteen, my brother Jem got his arm badly broken at the elbow...',
    readingProgress: 60,
  },
  {
    id: '3',
    title: '1984',
    author: 'George Orwell',
    coverImage: 'https://placehold.co/300x450/a0aec0/2d3748',
    'data-ai-hint': 'dystopian cover',
    description: 'A dystopian novel set in Airstrip One, a province of the superstate Oceania in a world of perpetual war, omnipresent government surveillance, and public manipulation.',
    tags: ['Dystopian', 'Sci-Fi', 'Political Fiction'],
    language: 'English',
    content: 'It was a bright cold day in April, and the clocks were striking thirteen...',
    readingProgress: 0,
  },
    {
    id: '4',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    coverImage: 'https://placehold.co/300x450/89b7e5/2a3f5c',
    'data-ai-hint': 'romantic novel',
    description: 'A romantic novel of manners that charts the emotional development of the protagonist Elizabeth Bennet, who learns the error of making hasty judgments.',
    tags: ['Classic', 'Romance', 'Satire'],
    language: 'English',
    content: 'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife...',
    readingProgress: 85,
  },
];
